### PR TITLE
Add pre-filters to adapter

### PR DESCRIPTION
**Pull request by thegecko**
As mentioned on #68 , this PR passes filters down to the adapter to shortcut building device lists.

cc @brandonros

### CODE REVIEW

**Comment by thegecko** [comment]
Does this fix your Windows issue?

**Comment by brandonros** [comment]
most likely yes

can you merge and release? i’ll test

**Comment by thegecko** [comment]
Merging it should create a preview on npm

**Comment by brandonros** [comment]
you don't have to do a `npm version minor && npm publish`? i'd expect a v2.0.3 or v2.1

thanks for doing this, really appreciate it. nice package, makes isomorphic code easy

**Comment by thegecko** [comment]
> you don't have to do a npm version minor && npm publish? i'd expect a v2.0.3 or v2.1

No, the build system does next versions. Here's one with those changes:

https://www.npmjs.com/package/webusb/v/2.0.3-next.0a3f331.0

**Pull request merged**
